#! /bin/sh

# Start-up script for VeritySigner

VERITYSIGNER_HOME=`dirname "$0"`
VERITYSIGNER_HOME=`dirname "$VERITYSIGNER_HOME"`

/usr/lib/jvm/java-7-openjdk-amd64/bin/java -Xmx512M -jar vendor/qcom/proprietary/b2g_common-noship/jar/VeritySigner.jar "$@"
